// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: camera_service.proto

#include "camera_service.pb.h"
#include "camera_service.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>

static const char* CameraDetectionService_method_names[] = {
  "/CameraDetectionService/Detect",
};

std::unique_ptr< CameraDetectionService::Stub> CameraDetectionService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< CameraDetectionService::Stub> stub(new CameraDetectionService::Stub(channel, options));
  return stub;
}

CameraDetectionService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_Detect_(CameraDetectionService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status CameraDetectionService::Stub::Detect(::grpc::ClientContext* context, const ::CameraDetectionRequest& request, ::CameraDetectionResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::CameraDetectionRequest, ::CameraDetectionResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Detect_, context, request, response);
}

void CameraDetectionService::Stub::async::Detect(::grpc::ClientContext* context, const ::CameraDetectionRequest* request, ::CameraDetectionResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::CameraDetectionRequest, ::CameraDetectionResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Detect_, context, request, response, std::move(f));
}

void CameraDetectionService::Stub::async::Detect(::grpc::ClientContext* context, const ::CameraDetectionRequest* request, ::CameraDetectionResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Detect_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::CameraDetectionResponse>* CameraDetectionService::Stub::PrepareAsyncDetectRaw(::grpc::ClientContext* context, const ::CameraDetectionRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::CameraDetectionResponse, ::CameraDetectionRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Detect_, context, request);
}

::grpc::ClientAsyncResponseReader< ::CameraDetectionResponse>* CameraDetectionService::Stub::AsyncDetectRaw(::grpc::ClientContext* context, const ::CameraDetectionRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncDetectRaw(context, request, cq);
  result->StartCall();
  return result;
}

CameraDetectionService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      CameraDetectionService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< CameraDetectionService::Service, ::CameraDetectionRequest, ::CameraDetectionResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](CameraDetectionService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::CameraDetectionRequest* req,
             ::CameraDetectionResponse* resp) {
               return service->Detect(ctx, req, resp);
             }, this)));
}

CameraDetectionService::Service::~Service() {
}

::grpc::Status CameraDetectionService::Service::Detect(::grpc::ServerContext* context, const ::CameraDetectionRequest* request, ::CameraDetectionResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


