# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: camera_service.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='camera_service.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x14\x63\x61mera_service.proto\"\x18\n\x16\x43\x61meraDetectionRequest\"\\\n\x0e\x44\x65tectedObject\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02\x12\x0c\n\x04time\x18\x03 \x01(\x01\x12\n\n\x02\x64x\x18\x04 \x01(\x02\x12\n\n\x02\x64y\x18\x05 \x01(\x02\x12\x0e\n\x06length\x18\x06 \x01(\x02\"D\n\x17\x43\x61meraDetectionResponse\x12)\n\x10\x64\x65tected_objects\x18\x01 \x03(\x0b\x32\x0f.DetectedObject2W\n\x16\x43\x61meraDetectionService\x12=\n\x06\x44\x65tect\x12\x17.CameraDetectionRequest\x1a\x18.CameraDetectionResponse\"\x00\x62\x06proto3'
)




_CAMERADETECTIONREQUEST = _descriptor.Descriptor(
  name='CameraDetectionRequest',
  full_name='CameraDetectionRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=24,
  serialized_end=48,
)


_DETECTEDOBJECT = _descriptor.Descriptor(
  name='DetectedObject',
  full_name='DetectedObject',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='DetectedObject.x', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='y', full_name='DetectedObject.y', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='time', full_name='DetectedObject.time', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='dx', full_name='DetectedObject.dx', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='dy', full_name='DetectedObject.dy', index=4,
      number=5, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='length', full_name='DetectedObject.length', index=5,
      number=6, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=50,
  serialized_end=142,
)


_CAMERADETECTIONRESPONSE = _descriptor.Descriptor(
  name='CameraDetectionResponse',
  full_name='CameraDetectionResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='detected_objects', full_name='CameraDetectionResponse.detected_objects', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=144,
  serialized_end=212,
)

_CAMERADETECTIONRESPONSE.fields_by_name['detected_objects'].message_type = _DETECTEDOBJECT
DESCRIPTOR.message_types_by_name['CameraDetectionRequest'] = _CAMERADETECTIONREQUEST
DESCRIPTOR.message_types_by_name['DetectedObject'] = _DETECTEDOBJECT
DESCRIPTOR.message_types_by_name['CameraDetectionResponse'] = _CAMERADETECTIONRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CameraDetectionRequest = _reflection.GeneratedProtocolMessageType('CameraDetectionRequest', (_message.Message,), {
  'DESCRIPTOR' : _CAMERADETECTIONREQUEST,
  '__module__' : 'camera_service_pb2'
  # @@protoc_insertion_point(class_scope:CameraDetectionRequest)
  })
_sym_db.RegisterMessage(CameraDetectionRequest)

DetectedObject = _reflection.GeneratedProtocolMessageType('DetectedObject', (_message.Message,), {
  'DESCRIPTOR' : _DETECTEDOBJECT,
  '__module__' : 'camera_service_pb2'
  # @@protoc_insertion_point(class_scope:DetectedObject)
  })
_sym_db.RegisterMessage(DetectedObject)

CameraDetectionResponse = _reflection.GeneratedProtocolMessageType('CameraDetectionResponse', (_message.Message,), {
  'DESCRIPTOR' : _CAMERADETECTIONRESPONSE,
  '__module__' : 'camera_service_pb2'
  # @@protoc_insertion_point(class_scope:CameraDetectionResponse)
  })
_sym_db.RegisterMessage(CameraDetectionResponse)



_CAMERADETECTIONSERVICE = _descriptor.ServiceDescriptor(
  name='CameraDetectionService',
  full_name='CameraDetectionService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=214,
  serialized_end=301,
  methods=[
  _descriptor.MethodDescriptor(
    name='Detect',
    full_name='CameraDetectionService.Detect',
    index=0,
    containing_service=None,
    input_type=_CAMERADETECTIONREQUEST,
    output_type=_CAMERADETECTIONRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_CAMERADETECTIONSERVICE)

DESCRIPTOR.services_by_name['CameraDetectionService'] = _CAMERADETECTIONSERVICE

# @@protoc_insertion_point(module_scope)
